concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Mr.Anderson"
  url = "https://gitlab.com/"
  token = "sn_gLaPyXbxAFrE4wHAw"
  executor = "ssh"
  [runners.custom_build_dir]
  [runners.ssh]
    user = "root"
    password = "evitar.io"
    host = "my.server.com"
    port = "22"
    identity_file = "evitar.io"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "Mr.Anderson"
  url = "https://gitlab.com/"
  token = "u-oN2yfhN23oGjw3zxXB"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "Morpheus"
  url = "https://gitlab.com/"
  token = "m5qxnefH6WFGTfcRJ9uN"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "Trinity"
  url = "https://gitlab.com/"
  token = "1s8sTbH-k8Xwr7tgV51w"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
